library ALibraryTestDesyncDesync requires AStructCoreGeneralGroup, ALibraryCoreDebugMisc, AStructCoreInterfaceVolumeSet, ALibraryCoreInterfaceCamera, ALibraryCoreInterfaceMisc, ALibraryCoreInterfaceMusic, ALibraryCoreEnvironmentTerrainFog

	/**
	 * 2012-12-15 works all, no desync!
	 */
	function ADesyncDebug takes nothing returns nothing
		local player whichPlayer = Player(0)
		local location whichLocation = Location(0.0, 0.0)
		local AVolumeSet volumeSet = AVolumeSet.create()
		local unit whichUnit = CreateUnit(Player(0), 'hpea', 0.0, 0.0, 0.0)
		local AGroup whichGroup = AGroup.create()
		debug call Print("ResetTerrainFogForPlayer")
		call ResetTerrainFogForPlayer(whichPlayer)
		debug call Print("PanCameraToWithZForPlayer")
		call PanCameraToWithZForPlayer(whichPlayer, 0.0, 0.0, 2.0)
		debug call Print("PanCameraToTimedWithZForPlayer")
		call PanCameraToTimedWithZForPlayer(whichPlayer, 0.0, 0.0, 2.0, 4.0)
		debug call Print("SmartCameraPanForPlayer")
		call SmartCameraPanForPlayer(whichPlayer, 0.0, 0.0, 4.0)
		debug call Print("SmartCameraPanWithZForPlayer")
		call SmartCameraPanWithZForPlayer(whichPlayer, 0.0, 0.0, 2.0, 4.0)
		debug call Print("RotateCameraAroundForPlayer")
		call RotateCameraAroundForPlayer(whichPlayer, 0.0, 0.0, 30.0, 4.0)
		debug call Print("SetCameraPositionLocationForPlayer")
		call SetCameraPositionLocationForPlayer(whichPlayer, whichLocation)
		debug call Print("SetCameraQuickPositionLocationForPlayer")
		call SetCameraQuickPositionLocationForPlayer(whichPlayer, whichLocation)
		debug call Print("PanCameraToLocationForPlayer")
		call PanCameraToLocationForPlayer(whichPlayer, whichLocation)
		debug call Print("PanCameraToLocationWithZForPlayer")
		call PanCameraToLocationWithZForPlayer(whichPlayer, whichLocation, 2.0)
		debug call Print("PanCameraToTimedLocationForPlayer")
		call PanCameraToTimedLocationForPlayer(whichPlayer, whichLocation, 4.0)
		debug call Print("PanCameraToTimedLocationWithZForPlayer")
		call PanCameraToTimedLocationWithZForPlayer(whichPlayer, whichLocation, 1.0, 4.0)
		debug call Print("RotateCameraAroundLocationForPlayer")
		call RotateCameraAroundLocationForPlayer(whichPlayer, whichLocation, 30.0, 3.0)
		debug call Print("ResetCameraBoundsToMapRectForPlayer")
		call ResetCameraBoundsToMapRectForPlayer(whichPlayer)
		call TriggerSleepAction(5.0)
		debug call Print("AVolumeSet")
		call volumeSet.setCineModeVolume()
		call volumeSet.applyForPlayer(Player(0))
		call TriggerSleepAction(5.0)
		debug call Print("Clears and stops map music for all players.")
		call ClearMapMusic()
		call StopMusic(false)
		call TriggerSleepAction(5.0)
		debug call Print("Plays ArthasTheme or OrcTheme for player 0.")
		call SetMapMusicForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3;Sound\\Music\\mp3Music\\OrcTheme.mp3", true, 0)
		call TriggerSleepAction(5.0)
		debug call Print("Plays ArthasTheme for player 0.")
		call SetMapMusicIndexedForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3;Sound\\Music\\mp3Music\\OrcTheme.mp3", 0)
		call TriggerSleepAction(5.0)
		debug call Print("Plays ArthasTheme OR (randomly) OrcTheme for player 0.")
		call SetMapMusicRandomForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3;Sound\\Music\\mp3Music\\OrcTheme.mp3")
		call TriggerSleepAction(5.0)
		debug call Print("Clears music list for player 0.")
		call ClearMapMusicForPlayer(Player(0))
		call TriggerSleepAction(5.0)
		debug call Print("Plays ArthasTheme for player 0.")
		call PlayMusicForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3")
		call TriggerSleepAction(5.0)
		debug call Print("Plays ArthasTheme starting at 10 seconds and fading in with 10 seconds player 0")
		call PlayMusicExForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3", 10000, 10000)
		call TriggerSleepAction(25.0)
		debug call Print("Stops music with fading out for player 0.")
		call StopMusicForPlayer(Player(0), true)
		call TriggerSleepAction(10.0)
		debug call Print("Resumes music for player 0.")
		call ResumeMusicForPlayer(Player(0))
		call TriggerSleepAction(5.0)
		debug call Print("Plays thematic ArthasTheme for player 0.")
		call PlayThematicMusicForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3")
		call TriggerSleepAction(5.0)
		debug call Print("Plays thematic ArthasTheme for player 0 starting at 10 seconds.")
		call PlayThematicMusicExForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3", 10000)
		call TriggerSleepAction(5.0)
		debug call Print("End thematic ArthasTheme for player 0.")
		call EndThematicMusicForPlayer(Player(0))
		call TriggerSleepAction(10.0)
		debug call Print("Set music volume to 0 for player 0.")
		call SetMusicVolumeForPlayer(Player(0), 0)
		call TriggerSleepAction(5.0)
		debug call Print("Set music volume to 127 for player 0.")
		call SetMusicVolumeForPlayer(Player(0), 127)
		call TriggerSleepAction(10.0)
		debug call Print("Set play position to 20 seconds.")
		call SetMusicPlayPositionForPlayer(Player(0), 20000)
		call TriggerSleepAction(10.0)
		debug call Print("Play ArthasTheme for player 0.")
		call PlayThematicMusicForPlayer(Player(0), "Sound\\Music\\mp3Music\\ArthasTheme.mp3")
		call TriggerSleepAction(5.0)
		debug call Print("Set ArthasTheme play position to 20 seconds.")
		call SetThematicMusicPlayPositionForPlayer(Player(0), 20000)


		call ResetToGameCameraForPlayer(whichPlayer, 0.0)

		call TriggerSleepAction(10.0)
		debug call Print("Setting terrain fog to night for all players.")
		call SetTerrainFogNight()
		call TriggerSleepAction(5.0)
		debug call Print("Resetting terrain fog for player 0.")
		call ResetTerrainFogForPlayer(Player(0))

		call TriggerSleepAction(5.0)
		debug call Print("IsInGame().")
		call IsInGame()
		call TriggerSleepAction(5.0)
		debug call Print("IsInGameEx().")
		call IsInGameEx()
		call TriggerSleepAction(5.0)
		debug call Print("Select unit for player 0.")
		call whichGroup.units().pushBack(whichUnit)
		call whichGroup.selectOnlyForPlayer(Player(0))

		call TriggerSleepAction(10.0)
		debug call Print("Changing worker vertex color for player 0.")
		call SetUnitVertexColourForPlayer(Player(0), whichUnit, 100.0, 10.0, 10.0, 50.0)
		call TriggerSleepAction(5.0)
		debug call Print("Hiding for player 0.")
		call ShowUnitForPlayer(Player(0), whichUnit, false)
		call TriggerSleepAction(5.0)
		/*
		DESYNC!
		debug call Print("Set terrain fog to forest for player 0.")
		if (GetLocalPlayer() == Player(0)) then
			call SetTerrainFogForest()
		endif
		*/

		debug call Print("END OF TEST! handle id of SOUND_VOLUMEGROUP_FIRE is " + I2S(GetHandleId(SOUND_VOLUMEGROUP_FIRE)))

		set whichPlayer = null
		call RemoveLocation(whichLocation)
		set whichLocation = null
		call RemoveUnit(whichUnit)
		set whichUnit = null
	endfunction

endlibrary