#!/bin/bash

if [ -z "$1" ] || [ ! -e "$1" ]; then
	echo "Usage: $0 <icon file>" >&2
	exit 1
fi
#-font dfst-m3u.ttf -pointsize 40 label:"$i"
for ((i=1; i < 6; i++)) do
	composite \( -gravity SouthEast human-button-lvls-overlay.png \) "$1" "$(basename "$1")Level$i.png"
done
