//===========================================================================
// 
// Kapitel 2: Gardonar 1.0
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Mon Oct 30 09:02:23 2017
//   Map Author: Tamino Dauth
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

globals
    // User-defined
    effect array            udg_trapeffect

    // Generated
    rect                    gg_rct_area_playable       = null
    rect                    gg_rct_boat_glow           = null
    rect                    gg_rct_main_window_credits = null
    rect                    gg_rct_main_window_info_log = null
    rect                    gg_rct_quest_palace_fight_through_hell = null
    rect                    gg_rct_quest_palace_gather = null
    rect                    gg_rct_quest_palace_gather_inside = null
    rect                    gg_rct_quest_palace_guard_position_0 = null
    rect                    gg_rct_quest_palace_guard_position_1 = null
    rect                    gg_rct_quest_palace_guard_position_2 = null
    rect                    gg_rct_quest_palace_guard_position_3 = null
    rect                    gg_rct_quest_palace_guard_position_4 = null
    rect                    gg_rct_quest_palace_guard_position_5 = null
    rect                    gg_rct_shrine_end_discover = null
    rect                    gg_rct_shrine_end_revival  = null
    rect                    gg_rct_shrine_start_discover = null
    rect                    gg_rct_shrine_start_revival = null
    rect                    gg_rct_start               = null
    rect                    gg_rct_start_hell          = null
    rect                    gg_rct_trap_0              = null
    rect                    gg_rct_trap_1              = null
    rect                    gg_rct_trap_2              = null
    rect                    gg_rct_trap_3              = null
    rect                    gg_rct_trap_4              = null
    rect                    gg_rct_trap_5              = null
    rect                    gg_rct_trap_6              = null
    rect                    gg_rct_trap_7              = null
    rect                    gg_rct_video_intro_actor   = null
    rect                    gg_rct_video_palace_actor  = null
    rect                    gg_rct_video_palace_dragon_slayer = null
    rect                    gg_rct_video_palace_ricman = null
    rect                    gg_rct_video_palace_wigberht = null
    rect                    gg_rct_video_welcome_actor = null
    rect                    gg_rct_zombies             = null
    rect                    gg_rct_zone_gardonars_hell = null
    rect                    gg_rct_zone_talras         = null
    rect                    gg_rct_class_selection     = null
    camerasetup             gg_cam_class_selection     = null
    camerasetup             gg_cam_intro_0             = null
    camerasetup             gg_cam_intro_1             = null
    camerasetup             gg_cam_main_window         = null
    camerasetup             gg_cam_the_gate_0          = null
    camerasetup             gg_cam_the_gate_1          = null
    camerasetup             gg_cam_the_gate_2          = null
    camerasetup             gg_cam_the_gate_3          = null
    camerasetup             gg_cam_the_gate_4          = null
    camerasetup             gg_cam_welcome_0           = null
    camerasetup             gg_cam_welcome_1           = null
    sound                   gg_snd_SoulPreservation    = null
    trigger                 gg_trg_Traps_0             = null
    trigger                 gg_trg_Traps_1             = null
    trigger                 gg_trg_Traps_2             = null
    trigger                 gg_trg_Traps_3             = null
    trigger                 gg_trg_Traps_4             = null
    trigger                 gg_trg_Traps_5             = null
    trigger                 gg_trg_Traps_6             = null
    trigger                 gg_trg_Traps_7             = null
    trigger                 gg_trg_Intro               = null
    trigger                 gg_trg_The_Gate            = null
    trigger                 gg_trg_Shrines             = null
    trigger                 gg_trg_Npcs                = null
    trigger                 gg_trg_Palace              = null
    trigger                 gg_trg_Demon_Heroes        = null
    trigger                 gg_trg_Spawns              = null
    trigger                 gg_trg_Goldmine            = null
    unit                    gg_unit_u00A_0006          = null
    unit                    gg_unit_n06W_0007          = null
    unit                    gg_unit_n06V_0008          = null
    unit                    gg_unit_n06U_0005          = null
    unit                    gg_unit_H01E_0009          = null
    unit                    gg_unit_H01C_0003          = null
    unit                    gg_unit_H01F_0004          = null
    unit                    gg_unit_n06X_0016          = null
    unit                    gg_unit_n06X_0017          = null
    unit                    gg_unit_n06Y_0023          = null
    unit                    gg_unit_n06Y_0024          = null
    unit                    gg_unit_n070_0034          = null
    unit                    gg_unit_n070_0035          = null
    unit                    gg_unit_n071_0039          = null
    unit                    gg_unit_n072_0040          = null
    unit                    gg_unit_n072_0041          = null
    unit                    gg_unit_n072_0042          = null
    unit                    gg_unit_n073_0043          = null
    unit                    gg_unit_n073_0044          = null
    unit                    gg_unit_n073_0045          = null
    unit                    gg_unit_n073_0046          = null
    unit                    gg_unit_n073_0047          = null
    unit                    gg_unit_n073_0048          = null
    unit                    gg_unit_n073_0049          = null
    unit                    gg_unit_n073_0050          = null
    unit                    gg_unit_n073_0051          = null
    unit                    gg_unit_n073_0052          = null
    unit                    gg_unit_n073_0053          = null
    unit                    gg_unit_n073_0054          = null
    unit                    gg_unit_n073_0055          = null
    unit                    gg_unit_n073_0056          = null
    unit                    gg_unit_n073_0057          = null
    unit                    gg_unit_n073_0058          = null
    unit                    gg_unit_n073_0059          = null
    unit                    gg_unit_n073_0060          = null
    unit                    gg_unit_n04D_0061          = null
    unit                    gg_unit_n04D_0062          = null
    unit                    gg_unit_n04C_0063          = null
    unit                    gg_unit_n02D_0064          = null
    unit                    gg_unit_n04D_0065          = null
    unit                    gg_unit_n04D_0066          = null
    unit                    gg_unit_n04D_0067          = null
    unit                    gg_unit_n04C_0068          = null
    unit                    gg_unit_n073_0069          = null
    unit                    gg_unit_n073_0070          = null
    unit                    gg_unit_n073_0071          = null
    unit                    gg_unit_n073_0072          = null
    unit                    gg_unit_n073_0073          = null
    unit                    gg_unit_n073_0074          = null
    unit                    gg_unit_n073_0075          = null
    unit                    gg_unit_n073_0076          = null
    unit                    gg_unit_n073_0077          = null
    unit                    gg_unit_n073_0078          = null
    unit                    gg_unit_n073_0079          = null
    unit                    gg_unit_n073_0080          = null
    unit                    gg_unit_n073_0081          = null
    unit                    gg_unit_n073_0082          = null
    unit                    gg_unit_n073_0083          = null
    unit                    gg_unit_n073_0084          = null
    unit                    gg_unit_n02D_0085          = null
    unit                    gg_unit_n073_0087          = null
    unit                    gg_unit_n073_0088          = null
    unit                    gg_unit_n073_0089          = null
    unit                    gg_unit_n073_0090          = null
    unit                    gg_unit_n073_0091          = null
    unit                    gg_unit_n07A_0092          = null
    unit                    gg_unit_n07A_0093          = null
    unit                    gg_unit_n07A_0094          = null
    unit                    gg_unit_n07A_0095          = null
    unit                    gg_unit_n07A_0096          = null
    unit                    gg_unit_n07B_0097          = null
    unit                    gg_unit_n07B_0098          = null
    unit                    gg_unit_n078_0099          = null
    unit                    gg_unit_n078_0100          = null
    unit                    gg_unit_n078_0101          = null
    unit                    gg_unit_n078_0102          = null
    unit                    gg_unit_n078_0103          = null
    unit                    gg_unit_n078_0104          = null
    unit                    gg_unit_n078_0105          = null
    unit                    gg_unit_n078_0106          = null
    unit                    gg_unit_n078_0107          = null
    unit                    gg_unit_n078_0108          = null
    unit                    gg_unit_n078_0109          = null
    unit                    gg_unit_n078_0110          = null
    unit                    gg_unit_n078_0111          = null
    unit                    gg_unit_n078_0112          = null
    unit                    gg_unit_n078_0113          = null
    unit                    gg_unit_n079_0114          = null
    unit                    gg_unit_n079_0115          = null
    unit                    gg_unit_n079_0116          = null
    unit                    gg_unit_n07B_0117          = null
    unit                    gg_unit_n07B_0118          = null
    unit                    gg_unit_n07B_0119          = null
    unit                    gg_unit_n072_0121          = null
    unit                    gg_unit_n072_0122          = null
    unit                    gg_unit_n078_0123          = null
    unit                    gg_unit_n078_0124          = null
    unit                    gg_unit_n07B_0125          = null
    unit                    gg_unit_n07B_0126          = null
    unit                    gg_unit_n07A_0127          = null
    unit                    gg_unit_n07A_0128          = null
    unit                    gg_unit_n07A_0129          = null
    unit                    gg_unit_n073_0130          = null
    unit                    gg_unit_n073_0131          = null
    unit                    gg_unit_n073_0132          = null
    unit                    gg_unit_n04B_0136          = null
    unit                    gg_unit_n04B_0137          = null
    unit                    gg_unit_n04B_0138          = null
    unit                    gg_unit_n04C_0139          = null
    unit                    gg_unit_n04C_0140          = null
    unit                    gg_unit_n04D_0141          = null
    unit                    gg_unit_n02C_0142          = null
    unit                    gg_unit_n02C_0143          = null
    unit                    gg_unit_n02C_0144          = null
    unit                    gg_unit_n02C_0145          = null
    unit                    gg_unit_n02C_0146          = null
    unit                    gg_unit_n02C_0147          = null
    unit                    gg_unit_n032_0148          = null
    unit                    gg_unit_n032_0149          = null
    unit                    gg_unit_n04D_0150          = null
    unit                    gg_unit_n04D_0151          = null
    unit                    gg_unit_n04D_0152          = null
    unit                    gg_unit_n04C_0153          = null
    unit                    gg_unit_n04C_0154          = null
    unit                    gg_unit_n04C_0155          = null
    unit                    gg_unit_n04D_0156          = null
    unit                    gg_unit_n02C_0157          = null
    unit                    gg_unit_n02C_0158          = null
    unit                    gg_unit_n06E_0161          = null
    destructable            gg_dest_DTg5_0000          = null
    destructable            gg_dest_B008_0133          = null
    destructable            gg_dest_B008_0267          = null
    destructable            gg_dest_DTfp_1658          = null
    destructable            gg_dest_DTfp_1659          = null
    destructable            gg_dest_DTfp_1660          = null
    destructable            gg_dest_DTfp_1700          = null
    destructable            gg_dest_DTfp_1720          = null
    destructable            gg_dest_DTfp_1721          = null
    destructable            gg_dest_DTfp_1722          = null
    destructable            gg_dest_DTfp_1723          = null
    destructable            gg_dest_DTfp_1728          = null
    destructable            gg_dest_DTfp_1725          = null
    destructable            gg_dest_DTfp_1726          = null
    destructable            gg_dest_DTfp_1727          = null
    destructable            gg_dest_DTfp_2144          = null
    destructable            gg_dest_DTfp_2145          = null
    destructable            gg_dest_DTfp_2146          = null
    destructable            gg_dest_DTfp_2147          = null
    destructable            gg_dest_DTfp_2148          = null
    destructable            gg_dest_DTfp_2149          = null
    destructable            gg_dest_DTfp_2150          = null
    destructable            gg_dest_DTfp_2151          = null
    destructable            gg_dest_DTfp_2152          = null
    destructable            gg_dest_DTfp_2153          = null
    destructable            gg_dest_DTfp_2154          = null
    destructable            gg_dest_DTfp_2155          = null
    destructable            gg_dest_DTfp_2156          = null
    destructable            gg_dest_DTfp_2157          = null
    destructable            gg_dest_DTfp_2158          = null
    destructable            gg_dest_DTfp_2159          = null
    destructable            gg_dest_DTfp_2160          = null
    destructable            gg_dest_DTfp_2161          = null
    destructable            gg_dest_DTfp_2162          = null
    destructable            gg_dest_DTfp_2163          = null
endglobals

function InitGlobals takes nothing returns nothing
    local integer i = 0
endfunction

//***************************************************************************
//*
//*  Sounds
//*
//***************************************************************************

function InitSounds takes nothing returns nothing
    set gg_snd_SoulPreservation = CreateSound( "Abilities\\Spells\\Demon\\SoulPreservation\\SoulPreservation.wav", false, true, true, 10, 10, "SpellsEAX" )
    call SetSoundParamsFromLabel( gg_snd_SoulPreservation, "SoulPreservation" )
    call SetSoundDuration( gg_snd_SoulPreservation, 3613 )
endfunction

//***************************************************************************
//*
//*  Destructable Objects
//*
//***************************************************************************

function CreateAllDestructables takes nothing returns nothing
    local destructable d
    local trigger t
    local real life
    set gg_dest_B008_0133 = CreateDestructable( 'B008', -1472.0, 1216.0, 291.732, 2.000, 0 )
    set gg_dest_B008_0267 = CreateDestructable( 'B008', 512.0, 576.0, 132.157, 2.000, 0 )
    set gg_dest_DTfp_2146 = CreateDestructable( 'DTfp', 4544.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1658 = CreateDestructable( 'DTfp', 5440.0, 2368.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1659 = CreateDestructable( 'DTfp', 5440.0, 2496.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1660 = CreateDestructable( 'DTfp', 5312.0, 2496.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1700 = CreateDestructable( 'DTfp', 5312.0, 2368.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1720 = CreateDestructable( 'DTfp', 5248.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1721 = CreateDestructable( 'DTfp', 5120.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1722 = CreateDestructable( 'DTfp', 5120.0, 1600.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1723 = CreateDestructable( 'DTfp', 5248.0, 1600.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1728 = CreateDestructable( 'DTfp', 5824.0, 1984.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1725 = CreateDestructable( 'DTfp', 5952.0, 2112.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1726 = CreateDestructable( 'DTfp', 5952.0, 1984.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_1727 = CreateDestructable( 'DTfp', 5824.0, 2112.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2144 = CreateDestructable( 'DTfp', 4416.0, 1600.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2145 = CreateDestructable( 'DTfp', 4416.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2163 = CreateDestructable( 'DTfp', 3392.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2147 = CreateDestructable( 'DTfp', 4544.0, 1600.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2148 = CreateDestructable( 'DTfp', 3648.0, 1856.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2149 = CreateDestructable( 'DTfp', 3776.0, 1856.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2150 = CreateDestructable( 'DTfp', 3648.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2151 = CreateDestructable( 'DTfp', 3776.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2152 = CreateDestructable( 'DTfp', 3904.0, 1472.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2153 = CreateDestructable( 'DTfp', 4032.0, 1472.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2154 = CreateDestructable( 'DTfp', 3904.0, 1344.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2155 = CreateDestructable( 'DTfp', 4032.0, 1344.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2156 = CreateDestructable( 'DTfp', 3392.0, 1472.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2157 = CreateDestructable( 'DTfp', 3520.0, 1472.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2158 = CreateDestructable( 'DTfp', 3392.0, 1344.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2159 = CreateDestructable( 'DTfp', 3520.0, 1344.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2160 = CreateDestructable( 'DTfp', 3264.0, 1856.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2161 = CreateDestructable( 'DTfp', 3392.0, 1856.0, 270.000, 1.000, 0 )
    set gg_dest_DTfp_2162 = CreateDestructable( 'DTfp', 3264.0, 1728.0, 270.000, 1.000, 0 )
    set gg_dest_DTg5_0000 = CreateDestructable( 'DTg5', -896.0, 2688.0, 270.000, 0.900, 0 )
endfunction

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateNeutralHostile takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set gg_unit_n071_0039 = CreateUnit( p, 'n071', 2274.3, 6568.0, 315.894 )
    set gg_unit_n072_0040 = CreateUnit( p, 'n072', 2598.0, 4077.6, 325.084 )
    set gg_unit_n072_0041 = CreateUnit( p, 'n072', 2855.5, 4117.8, 31.729 )
    set gg_unit_n072_0042 = CreateUnit( p, 'n072', 2704.8, 4158.6, 212.174 )
    set gg_unit_n073_0043 = CreateUnit( p, 'n073', 2789.5, 6408.8, 298.280 )
    set gg_unit_n073_0044 = CreateUnit( p, 'n073', 2498.3, 6229.2, 306.858 )
    set gg_unit_n073_0045 = CreateUnit( p, 'n073', 2608.5, 6399.9, 314.156 )
    set gg_unit_n073_0046 = CreateUnit( p, 'n073', 2291.0, 6283.1, 316.692 )
    set gg_unit_n073_0047 = CreateUnit( p, 'n073', 2453.4, 6478.3, 311.115 )
    set gg_unit_n073_0048 = CreateUnit( p, 'n073', 3007.2, 6910.6, 308.145 )
    set gg_unit_n073_0049 = CreateUnit( p, 'n073', 2183.8, 6187.4, 305.329 )
    set gg_unit_n073_0050 = CreateUnit( p, 'n073', 2916.3, 7061.4, 298.748 )
    set gg_unit_n073_0051 = CreateUnit( p, 'n073', 2551.2, 6654.5, 307.601 )
    set gg_unit_n073_0052 = CreateUnit( p, 'n073', 2947.9, 6673.9, 312.921 )
    set gg_unit_n073_0053 = CreateUnit( p, 'n073', 2334.5, 6028.5, 297.758 )
    set gg_unit_n073_0054 = CreateUnit( p, 'n073', 2364.0, 6408.8, 328.536 )
    set gg_unit_n073_0055 = CreateUnit( p, 'n073', 2840.6, 6565.1, 309.042 )
    set gg_unit_n073_0056 = CreateUnit( p, 'n073', 2732.5, 6687.0, 305.946 )
    set gg_unit_n073_0057 = CreateUnit( p, 'n073', 2196.3, 5888.1, 302.615 )
    set gg_unit_n073_0058 = CreateUnit( p, 'n073', 2837.3, 6907.1, 310.970 )
    set gg_unit_n073_0059 = CreateUnit( p, 'n073', 2616.8, 6834.3, 304.833 )
    set gg_unit_n073_0060 = CreateUnit( p, 'n073', 2084.2, 6033.7, 319.946 )
    set gg_unit_n04D_0061 = CreateUnit( p, 'n04D', -1352.2, 2524.7, 69.392 )
    call SetUnitColor( gg_unit_n04D_0061, ConvertPlayerColor(12) )
    set gg_unit_n04D_0062 = CreateUnit( p, 'n04D', -1283.6, 2551.2, 127.346 )
    call SetUnitColor( gg_unit_n04D_0062, ConvertPlayerColor(12) )
    set gg_unit_n04C_0063 = CreateUnit( p, 'n04C', -1295.8, 2446.1, 143.464 )
    call SetUnitColor( gg_unit_n04C_0063, ConvertPlayerColor(12) )
    set gg_unit_n04D_0065 = CreateUnit( p, 'n04D', 645.2, 4850.2, 92.980 )
    call SetUnitColor( gg_unit_n04D_0065, ConvertPlayerColor(12) )
    set gg_unit_n04D_0066 = CreateUnit( p, 'n04D', 705.0, 4827.7, 63.558 )
    call SetUnitColor( gg_unit_n04D_0066, ConvertPlayerColor(12) )
    set gg_unit_n04D_0067 = CreateUnit( p, 'n04D', 657.5, 4790.8, 27.489 )
    call SetUnitColor( gg_unit_n04D_0067, ConvertPlayerColor(12) )
    set gg_unit_n04C_0068 = CreateUnit( p, 'n04C', 716.9, 4741.3, 43.386 )
    call SetUnitColor( gg_unit_n04C_0068, ConvertPlayerColor(12) )
    set gg_unit_n073_0069 = CreateUnit( p, 'n073', -674.7, 7209.4, 340.561 )
    set gg_unit_n073_0070 = CreateUnit( p, 'n073', -446.8, 7317.8, 342.308 )
    set gg_unit_n073_0071 = CreateUnit( p, 'n073', -396.0, 7554.0, 351.796 )
    set gg_unit_n073_0072 = CreateUnit( p, 'n073', -701.1, 7578.7, 331.596 )
    set gg_unit_n073_0073 = CreateUnit( p, 'n073', -157.0, 7673.5, 338.347 )
    set gg_unit_n073_0074 = CreateUnit( p, 'n073', -614.1, 7788.4, 332.065 )
    set gg_unit_n073_0075 = CreateUnit( p, 'n073', -314.4, 7989.8, 312.031 )
    set gg_unit_n073_0076 = CreateUnit( p, 'n073', -177.0, 7337.0, 329.654 )
    set gg_unit_n073_0077 = CreateUnit( p, 'n073', -468.2, 6846.2, 330.523 )
    set gg_unit_n073_0078 = CreateUnit( p, 'n073', -710.7, 7024.7, 325.827 )
    set gg_unit_n073_0079 = CreateUnit( p, 'n073', 42.1, 7420.3, 340.422 )
    set gg_unit_n073_0080 = CreateUnit( p, 'n073', 294.8, 7832.4, 348.289 )
    set gg_unit_n073_0081 = CreateUnit( p, 'n073', -147.9, 7184.9, 334.978 )
    set gg_unit_n073_0082 = CreateUnit( p, 'n073', -367.3, 7064.6, 331.083 )
    set gg_unit_n073_0083 = CreateUnit( p, 'n073', 59.3, 7810.7, 322.539 )
    set gg_unit_n073_0084 = CreateUnit( p, 'n073', -95.0, 7982.5, 339.421 )
    set gg_unit_n073_0087 = CreateUnit( p, 'n073', 5825.8, 6720.3, 247.184 )
    set gg_unit_n073_0088 = CreateUnit( p, 'n073', 5985.3, 6790.1, 276.552 )
    set gg_unit_n073_0089 = CreateUnit( p, 'n073', 5691.3, 6800.8, 230.127 )
    set gg_unit_n073_0090 = CreateUnit( p, 'n073', 5658.9, 6201.0, 125.374 )
    set gg_unit_n073_0091 = CreateUnit( p, 'n073', 5883.1, 6243.0, 137.430 )
    set gg_unit_n07A_0092 = CreateUnit( p, 'n07A', 7468.7, 5199.0, 146.208 )
    set gg_unit_n07A_0093 = CreateUnit( p, 'n07A', 7349.1, 4936.1, 101.878 )
    set gg_unit_n07A_0094 = CreateUnit( p, 'n07A', 7219.9, 5007.0, 108.824 )
    set gg_unit_n07A_0095 = CreateUnit( p, 'n07A', 6449.4, 4840.6, 148.331 )
    set gg_unit_n07A_0096 = CreateUnit( p, 'n07A', 6297.3, 4854.6, 44.826 )
    set gg_unit_n07B_0097 = CreateUnit( p, 'n07B', 6345.4, 5017.4, 94.706 )
    set gg_unit_n07B_0098 = CreateUnit( p, 'n07B', 7259.9, 5263.2, 150.920 )
    set gg_unit_n078_0099 = CreateUnit( p, 'n078', 6002.3, 3390.2, 45.271 )
    set gg_unit_n078_0100 = CreateUnit( p, 'n078', 6103.6, 3323.9, 46.265 )
    set gg_unit_n078_0101 = CreateUnit( p, 'n078', 6246.2, 3268.5, 37.494 )
    set gg_unit_n078_0102 = CreateUnit( p, 'n078', 6431.4, 3205.5, 31.003 )
    set gg_unit_n078_0103 = CreateUnit( p, 'n078', 6562.8, 3131.2, 34.270 )
    set gg_unit_n078_0104 = CreateUnit( p, 'n078', 5890.5, 3234.6, 36.612 )
    set gg_unit_n078_0105 = CreateUnit( p, 'n078', 6034.0, 3190.0, 57.515 )
    set gg_unit_n078_0106 = CreateUnit( p, 'n078', 6175.2, 3137.7, 41.609 )
    set gg_unit_n078_0107 = CreateUnit( p, 'n078', 6346.0, 3078.1, 45.431 )
    set gg_unit_n078_0108 = CreateUnit( p, 'n078', 6483.6, 3003.7, 46.881 )
    set gg_unit_n078_0109 = CreateUnit( p, 'n078', 5777.6, 3107.3, 43.596 )
    set gg_unit_n078_0110 = CreateUnit( p, 'n078', 5959.1, 3048.1, 42.055 )
    set gg_unit_n078_0111 = CreateUnit( p, 'n078', 6108.9, 2971.5, 42.803 )
    set gg_unit_n078_0112 = CreateUnit( p, 'n078', 6266.0, 2917.8, 43.660 )
    set gg_unit_n078_0113 = CreateUnit( p, 'n078', 6421.2, 2865.3, 42.543 )
    set gg_unit_n079_0114 = CreateUnit( p, 'n079', 6210.6, 3563.8, 85.674 )
    set gg_unit_n079_0115 = CreateUnit( p, 'n079', 6431.8, 3476.5, 53.430 )
    set gg_unit_n079_0116 = CreateUnit( p, 'n079', 6592.8, 3384.0, 79.280 )
    set gg_unit_n07B_0117 = CreateUnit( p, 'n07B', 4489.4, 1889.4, 68.469 )
    set gg_unit_n07B_0118 = CreateUnit( p, 'n07B', 4299.8, 1792.5, 348.393 )
    set gg_unit_n07B_0119 = CreateUnit( p, 'n07B', 4571.6, 1395.1, 72.780 )
    set u = CreateUnit( p, 'n072', 2260.4, 1737.3, 14.396 )
    set gg_unit_n072_0121 = CreateUnit( p, 'n072', 2197.0, 1604.6, 358.220 )
    set gg_unit_n072_0122 = CreateUnit( p, 'n072', 2307.3, 1615.4, 2.208 )
    set gg_unit_n078_0123 = CreateUnit( p, 'n078', 2437.0, 1868.1, 358.961 )
    set gg_unit_n078_0124 = CreateUnit( p, 'n078', 2489.1, 1754.4, 11.669 )
    set gg_unit_n07B_0125 = CreateUnit( p, 'n07B', 2805.0, 1203.1, 29.212 )
    set gg_unit_n07B_0126 = CreateUnit( p, 'n07B', 2607.4, 1867.7, 24.854 )
    set gg_unit_n07A_0127 = CreateUnit( p, 'n07A', 2355.9, 1026.6, 11.715 )
    set gg_unit_n07A_0128 = CreateUnit( p, 'n07A', 2440.7, 1240.3, 357.352 )
    set gg_unit_n07A_0129 = CreateUnit( p, 'n07A', 2303.7, 1206.1, 63.927 )
    set gg_unit_n073_0130 = CreateUnit( p, 'n073', 2653.3, 1623.0, 47.462 )
    set gg_unit_n073_0131 = CreateUnit( p, 'n073', 2742.7, 1499.8, 35.300 )
    set gg_unit_n073_0132 = CreateUnit( p, 'n073', 2768.6, 1346.1, 7.945 )
    set u = CreateUnit( p, 'n032', 3020.4, 4139.1, 95.177 )
    call SetUnitColor( u, ConvertPlayerColor(12) )
    set u = CreateUnit( p, 'n032', 3091.3, 4241.3, 225.963 )
    call SetUnitColor( u, ConvertPlayerColor(12) )
    set u = CreateUnit( p, 'n04B', 3006.7, 4210.7, 13.052 )
    call SetUnitColor( u, ConvertPlayerColor(12) )
    set gg_unit_n04B_0136 = CreateUnit( p, 'n04B', 7511.2, 4967.4, 217.217 )
    call SetUnitColor( gg_unit_n04B_0136, ConvertPlayerColor(12) )
    set gg_unit_n04B_0137 = CreateUnit( p, 'n04B', 7509.4, 4905.1, 317.778 )
    call SetUnitColor( gg_unit_n04B_0137, ConvertPlayerColor(12) )
    set gg_unit_n04B_0138 = CreateUnit( p, 'n04B', 7460.3, 4939.2, 126.632 )
    call SetUnitColor( gg_unit_n04B_0138, ConvertPlayerColor(12) )
    set gg_unit_n04C_0139 = CreateUnit( p, 'n04C', 6195.4, 4793.9, 66.975 )
    call SetUnitColor( gg_unit_n04C_0139, ConvertPlayerColor(12) )
    set gg_unit_n04C_0140 = CreateUnit( p, 'n04C', 6280.1, 4717.0, 12.690 )
    call SetUnitColor( gg_unit_n04C_0140, ConvertPlayerColor(12) )
    set gg_unit_n04D_0141 = CreateUnit( p, 'n04D', 6166.0, 4872.7, 67.700 )
    call SetUnitColor( gg_unit_n04D_0141, ConvertPlayerColor(12) )
    set gg_unit_n02C_0142 = CreateUnit( p, 'n02C', 5555.4, 3057.6, 262.746 )
    call SetUnitColor( gg_unit_n02C_0142, ConvertPlayerColor(12) )
    set gg_unit_n02C_0143 = CreateUnit( p, 'n02C', 5644.1, 3149.6, 62.514 )
    call SetUnitColor( gg_unit_n02C_0143, ConvertPlayerColor(12) )
    set gg_unit_n02C_0144 = CreateUnit( p, 'n02C', 5644.1, 3065.9, 277.567 )
    call SetUnitColor( gg_unit_n02C_0144, ConvertPlayerColor(12) )
    set gg_unit_n02C_0145 = CreateUnit( p, 'n02C', 6366.6, 2366.6, 31.993 )
    call SetUnitColor( gg_unit_n02C_0145, ConvertPlayerColor(12) )
    set gg_unit_n02C_0146 = CreateUnit( p, 'n02C', 6279.1, 2471.3, 125.731 )
    call SetUnitColor( gg_unit_n02C_0146, ConvertPlayerColor(12) )
    set gg_unit_n02C_0147 = CreateUnit( p, 'n02C', 6260.5, 2363.2, 79.247 )
    call SetUnitColor( gg_unit_n02C_0147, ConvertPlayerColor(12) )
    set gg_unit_n032_0148 = CreateUnit( p, 'n032', 5584.2, 2969.3, 260.285 )
    call SetUnitColor( gg_unit_n032_0148, ConvertPlayerColor(12) )
    set gg_unit_n032_0149 = CreateUnit( p, 'n032', 5660.6, 2990.9, 42.661 )
    call SetUnitColor( gg_unit_n032_0149, ConvertPlayerColor(12) )
    set gg_unit_n04D_0150 = CreateUnit( p, 'n04D', 4468.7, 1092.4, 340.125 )
    call SetUnitColor( gg_unit_n04D_0150, ConvertPlayerColor(12) )
    set gg_unit_n04D_0151 = CreateUnit( p, 'n04D', 4397.4, 1156.8, 41.354 )
    call SetUnitColor( gg_unit_n04D_0151, ConvertPlayerColor(12) )
    set gg_unit_n04D_0152 = CreateUnit( p, 'n04D', 4365.5, 1071.3, 258.703 )
    call SetUnitColor( gg_unit_n04D_0152, ConvertPlayerColor(12) )
    set gg_unit_n04C_0153 = CreateUnit( p, 'n04C', 4492.3, 1178.6, 181.994 )
    call SetUnitColor( gg_unit_n04C_0153, ConvertPlayerColor(12) )
    set gg_unit_n04C_0154 = CreateUnit( p, 'n04C', 2271.5, 859.9, 109.438 )
    call SetUnitColor( gg_unit_n04C_0154, ConvertPlayerColor(12) )
    set gg_unit_n04C_0155 = CreateUnit( p, 'n04C', 2290.6, 780.7, 61.888 )
    call SetUnitColor( gg_unit_n04C_0155, ConvertPlayerColor(12) )
    set gg_unit_n04D_0156 = CreateUnit( p, 'n04D', 2227.2, 805.2, 203.792 )
    call SetUnitColor( gg_unit_n04D_0156, ConvertPlayerColor(12) )
    set gg_unit_n02C_0157 = CreateUnit( p, 'n02C', 2246.4, 680.7, 263.482 )
    call SetUnitColor( gg_unit_n02C_0157, ConvertPlayerColor(12) )
    set gg_unit_n02C_0158 = CreateUnit( p, 'n02C', 2325.0, 612.2, 115.118 )
    call SetUnitColor( gg_unit_n02C_0158, ConvertPlayerColor(12) )
endfunction

//===========================================================================
function CreateNeutralPassiveBuildings takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set gg_unit_n02D_0064 = CreateUnit( p, 'n02D', -1408.0, 1152.0, 270.000 )
    call SetUnitColor( gg_unit_n02D_0064, ConvertPlayerColor(12) )
    set gg_unit_n02D_0085 = CreateUnit( p, 'n02D', 576.0, 512.0, 270.000 )
    call SetUnitColor( gg_unit_n02D_0085, ConvertPlayerColor(12) )
    set u = CreateUnit( p, 'n04Y', -1024.0, 640.0, 270.000 )
    set u = CreateUnit( p, 'n04E', -1024.0, 448.0, 270.000 )
    set gg_unit_n06E_0161 = CreateUnit( p, 'n06E', 8256.0, -3520.0, 270.000 )
    call SetResourceAmount( gg_unit_n06E_0161, 12500 )
endfunction

//===========================================================================
function CreateNeutralPassive takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_PASSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'n02E', -1906.0, -657.0, 348.292 )
    call SetUnitColor( u, ConvertPlayerColor(12) )
    set gg_unit_H01C_0003 = CreateUnit( p, 'H01C', -1624.1, 941.2, 292.970 )
    call SetHeroLevel( gg_unit_H01C_0003, 30, false )
    call SetUnitState( gg_unit_H01C_0003, UNIT_STATE_MANA, 660 )
    call SetUnitColor( gg_unit_H01C_0003, ConvertPlayerColor(12) )
    set gg_unit_H01F_0004 = CreateUnit( p, 'H01F', -1757.0, 732.0, 335.860 )
    call SetHeroLevel( gg_unit_H01F_0004, 30, false )
    call SetUnitState( gg_unit_H01F_0004, UNIT_STATE_MANA, 1095 )
    set gg_unit_n06U_0005 = CreateUnit( p, 'n06U', -945.7, 4779.1, 275.959 )
    call SetUnitState( gg_unit_n06U_0005, UNIT_STATE_MANA, 0 )
    set gg_unit_u00A_0006 = CreateUnit( p, 'u00A', -1088.0, 4808.2, 282.843 )
    call SetUnitState( gg_unit_u00A_0006, UNIT_STATE_MANA, 0 )
    set gg_unit_n06W_0007 = CreateUnit( p, 'n06W', -830.7, 4814.7, 267.432 )
    call SetUnitState( gg_unit_n06W_0007, UNIT_STATE_MANA, 0 )
    set gg_unit_n06V_0008 = CreateUnit( p, 'n06V', -702.1, 4826.9, 268.764 )
    call SetUnitState( gg_unit_n06V_0008, UNIT_STATE_MANA, 0 )
    set gg_unit_H01E_0009 = CreateUnit( p, 'H01E', -1690.7, 834.5, 326.710 )
    call SetHeroLevel( gg_unit_H01E_0009, 30, false )
    call SetUnitState( gg_unit_H01E_0009, UNIT_STATE_MANA, 660 )
    set u = CreateUnit( p, 'n06Z', -489.9, 3129.6, 2.126 )
    set u = CreateUnit( p, 'n06X', -1082.9, 3902.1, 270.000 )
    set gg_unit_n06X_0016 = CreateUnit( p, 'n06X', -966.3, 3897.6, 270.000 )
    set gg_unit_n06X_0017 = CreateUnit( p, 'n06X', -818.8, 3896.3, 270.000 )
    set u = CreateUnit( p, 'n06X', -702.1, 3903.7, 270.000 )
    set u = CreateUnit( p, 'n06X', -578.1, 3921.9, 270.000 )
    set u = CreateUnit( p, 'n06X', -1199.7, 3902.7, 270.000 )
    set u = CreateUnit( p, 'n06Z', -1321.8, 3127.7, 180.576 )
    set gg_unit_n06Y_0023 = CreateUnit( p, 'n06Y', -1013.2, 2564.3, 270.000 )
    set gg_unit_n06Y_0024 = CreateUnit( p, 'n06Y', -786.4, 2550.2, 270.000 )
    set u = CreateUnit( p, 'n070', -1582.1, 4792.2, 0.000 )
    set u = CreateUnit( p, 'n070', -1572.9, 4674.3, 0.000 )
    set u = CreateUnit( p, 'n070', -1581.8, 4546.6, 0.000 )
    set u = CreateUnit( p, 'n070', -1572.3, 4418.1, 0.000 )
    set u = CreateUnit( p, 'n070', -1585.1, 4291.8, 0.000 )
    set u = CreateUnit( p, 'n070', -1587.3, 4178.9, 0.000 )
    set u = CreateUnit( p, 'n070', -1596.7, 4047.2, 0.000 )
    set u = CreateUnit( p, 'n070', -191.1, 4804.6, 180.000 )
    set u = CreateUnit( p, 'n070', -195.3, 4677.2, 180.000 )
    set gg_unit_n070_0034 = CreateUnit( p, 'n070', -186.2, 4550.0, 180.000 )
    set gg_unit_n070_0035 = CreateUnit( p, 'n070', -202.1, 4407.2, 180.000 )
    set u = CreateUnit( p, 'n070', -203.9, 4268.3, 180.000 )
    set u = CreateUnit( p, 'n070', -185.4, 4150.0, 180.000 )
    set u = CreateUnit( p, 'n070', -198.7, 4030.0, 180.000 )
    set u = CreateUnit( p, 'n02E', 1404.0, -1102.7, 179.994 )
    call SetUnitColor( u, ConvertPlayerColor(12) )
    set u = CreateUnit( p, 'n07W', -1369.9, 7735.4, 123.677 )
    set u = CreateUnit( p, 'n07W', -1373.7, 7397.8, 28.181 )
    set u = CreateUnit( p, 'n07W', -1384.9, 7033.8, 337.510 )
    set u = CreateUnit( p, 'n07W', -1372.9, 8042.9, 208.966 )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreateNeutralPassiveBuildings(  )
    call CreatePlayerBuildings(  )
    call CreateNeutralHostile(  )
    call CreateNeutralPassive(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Regions
//*
//***************************************************************************

function CreateRegions takes nothing returns nothing
    local weathereffect we

    set gg_rct_area_playable = Rect( -3456.0, -3008.0, 8256.0, 8864.0 )
    set gg_rct_boat_glow = Rect( 544.0, -1696.0, 2432.0, -736.0 )
    set we = AddWeatherEffect( gg_rct_boat_glow, 'LRma' )
    call EnableWeatherEffect( we, true )
    set gg_rct_main_window_credits = Rect( -3296.0, -4672.0, -1664.0, -2976.0 )
    set gg_rct_main_window_info_log = Rect( -1536.0, -4640.0, 96.0, -2944.0 )
    set gg_rct_quest_palace_fight_through_hell = Rect( 768.0, -576.0, 1568.0, -64.0 )
    set gg_rct_quest_palace_gather = Rect( -1280.0, 2048.0, -480.0, 2560.0 )
    set gg_rct_quest_palace_gather_inside = Rect( -1312.0, 4096.0, -512.0, 4608.0 )
    set gg_rct_quest_palace_guard_position_0 = Rect( -1184.0, 2496.0, -1152.0, 2528.0 )
    set gg_rct_quest_palace_guard_position_1 = Rect( -608.0, 2496.0, -576.0, 2528.0 )
    set gg_rct_quest_palace_guard_position_2 = Rect( -1120.0, 3776.0, -1088.0, 3808.0 )
    set gg_rct_quest_palace_guard_position_3 = Rect( -704.0, 3776.0, -672.0, 3808.0 )
    set gg_rct_quest_palace_guard_position_4 = Rect( -64.0, 4768.0, -32.0, 4800.0 )
    set gg_rct_quest_palace_guard_position_5 = Rect( -64.0, 4192.0, -32.0, 4224.0 )
    set gg_rct_shrine_end_discover = Rect( 384.0, 224.0, 800.0, 704.0 )
    set gg_rct_shrine_end_revival = Rect( 544.0, 384.0, 640.0, 480.0 )
    set gg_rct_shrine_start_discover = Rect( -1664.0, 960.0, -1184.0, 1408.0 )
    set gg_rct_shrine_start_revival = Rect( -1504.0, 992.0, -1408.0, 1088.0 )
    set gg_rct_start = Rect( -1728.0, 192.0, -1696.0, 224.0 )
    set gg_rct_start_hell = Rect( 1120.0, -192.0, 1152.0, -160.0 )
    set gg_rct_trap_0 = Rect( 5248.0, 2304.0, 5504.0, 2560.0 )
    set gg_rct_trap_1 = Rect( 5760.0, 1920.0, 6016.0, 2176.0 )
    set gg_rct_trap_2 = Rect( 5056.0, 1536.0, 5312.0, 1792.0 )
    set gg_rct_trap_3 = Rect( 4352.0, 1568.0, 4608.0, 1760.0 )
    set gg_rct_trap_4 = Rect( 3584.0, 1664.0, 3840.0, 1920.0 )
    set gg_rct_trap_5 = Rect( 3328.0, 1280.0, 3584.0, 1536.0 )
    set gg_rct_trap_6 = Rect( 3200.0, 1664.0, 3456.0, 1920.0 )
    set gg_rct_trap_7 = Rect( 3840.0, 1280.0, 4096.0, 1536.0 )
    set gg_rct_video_intro_actor = Rect( -1600.0, 736.0, -1568.0, 768.0 )
    set gg_rct_video_palace_actor = Rect( -928.0, 2336.0, -896.0, 2368.0 )
    set gg_rct_video_palace_dragon_slayer = Rect( -1184.0, 2336.0, -1152.0, 2368.0 )
    set gg_rct_video_palace_ricman = Rect( -800.0, 2336.0, -768.0, 2368.0 )
    set gg_rct_video_palace_wigberht = Rect( -1056.0, 2336.0, -1024.0, 2368.0 )
    set gg_rct_video_welcome_actor = Rect( -896.0, 4512.0, -864.0, 4544.0 )
    set gg_rct_zombies = Rect( -1792.0, 6752.0, 960.0, 8608.0 )
    set gg_rct_zone_gardonars_hell = Rect( 576.0, -640.0, 1824.0, -320.0 )
    set gg_rct_zone_talras = Rect( -2528.0, -224.0, -1216.0, 32.0 )
    set gg_rct_class_selection = Rect( -2592.0, -3904.0, -2560.0, -3872.0 )
endfunction

//***************************************************************************
//*
//*  Cameras
//*
//***************************************************************************

function CreateCameras takes nothing returns nothing

    set gg_cam_class_selection = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_class_selection, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_class_selection, CAMERA_FIELD_ROTATION, 251.1, 0.0 )
    call CameraSetupSetField( gg_cam_class_selection, CAMERA_FIELD_ANGLE_OF_ATTACK, 333.5, 0.0 )
    call CameraSetupSetField( gg_cam_class_selection, CAMERA_FIELD_TARGET_DISTANCE, 1000.0, 0.0 )
    call CameraSetupSetField( gg_cam_class_selection, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_class_selection, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_class_selection, CAMERA_FIELD_FARZ, 6000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_class_selection, -2494.2, -3804.9, 0.0 )

    set gg_cam_intro_0 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_intro_0, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_intro_0, CAMERA_FIELD_ROTATION, 69.2, 0.0 )
    call CameraSetupSetField( gg_cam_intro_0, CAMERA_FIELD_ANGLE_OF_ATTACK, 320.5, 0.0 )
    call CameraSetupSetField( gg_cam_intro_0, CAMERA_FIELD_TARGET_DISTANCE, 2657.3, 0.0 )
    call CameraSetupSetField( gg_cam_intro_0, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_intro_0, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_intro_0, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_intro_0, -1622.7, -249.7, 0.0 )

    set gg_cam_intro_1 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_intro_1, CAMERA_FIELD_ZOFFSET, 45.0, 0.0 )
    call CameraSetupSetField( gg_cam_intro_1, CAMERA_FIELD_ROTATION, 149.6, 0.0 )
    call CameraSetupSetField( gg_cam_intro_1, CAMERA_FIELD_ANGLE_OF_ATTACK, 337.1, 0.0 )
    call CameraSetupSetField( gg_cam_intro_1, CAMERA_FIELD_TARGET_DISTANCE, 416.5, 0.0 )
    call CameraSetupSetField( gg_cam_intro_1, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_intro_1, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_intro_1, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_intro_1, -1464.4, 703.8, 0.0 )

    set gg_cam_main_window = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_main_window, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_main_window, CAMERA_FIELD_ROTATION, 90.0, 0.0 )
    call CameraSetupSetField( gg_cam_main_window, CAMERA_FIELD_ANGLE_OF_ATTACK, 270.0, 0.0 )
    call CameraSetupSetField( gg_cam_main_window, CAMERA_FIELD_TARGET_DISTANCE, 2923.1, 0.0 )
    call CameraSetupSetField( gg_cam_main_window, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_main_window, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_main_window, CAMERA_FIELD_FARZ, 6050.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_main_window, -1729.8, -3559.0, 0.0 )

    set gg_cam_the_gate_0 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_the_gate_0, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_0, CAMERA_FIELD_ROTATION, 85.1, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_0, CAMERA_FIELD_ANGLE_OF_ATTACK, 324.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_0, CAMERA_FIELD_TARGET_DISTANCE, 1650.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_0, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_0, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_0, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_the_gate_0, -879.5, 2347.6, 0.0 )

    set gg_cam_the_gate_1 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_the_gate_1, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_1, CAMERA_FIELD_ROTATION, 90.3, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_1, CAMERA_FIELD_ANGLE_OF_ATTACK, 326.5, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_1, CAMERA_FIELD_TARGET_DISTANCE, 931.4, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_1, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_1, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_1, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_the_gate_1, -901.4, 2731.8, 0.0 )

    set gg_cam_the_gate_2 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_the_gate_2, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_2, CAMERA_FIELD_ROTATION, 86.4, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_2, CAMERA_FIELD_ANGLE_OF_ATTACK, 305.7, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_2, CAMERA_FIELD_TARGET_DISTANCE, 1239.7, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_2, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_2, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_2, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_the_gate_2, -894.9, 3065.9, 0.0 )

    set gg_cam_the_gate_3 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_the_gate_3, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_3, CAMERA_FIELD_ROTATION, 86.4, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_3, CAMERA_FIELD_ANGLE_OF_ATTACK, 305.7, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_3, CAMERA_FIELD_TARGET_DISTANCE, 1239.7, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_3, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_3, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_3, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_the_gate_3, -898.6, 3633.8, 0.0 )

    set gg_cam_the_gate_4 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_the_gate_4, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_4, CAMERA_FIELD_ROTATION, 148.6, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_4, CAMERA_FIELD_ANGLE_OF_ATTACK, 302.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_4, CAMERA_FIELD_TARGET_DISTANCE, 1815.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_4, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_4, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_the_gate_4, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_the_gate_4, -927.8, 4209.1, 0.0 )

    set gg_cam_welcome_0 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_welcome_0, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_0, CAMERA_FIELD_ROTATION, 1.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_0, CAMERA_FIELD_ANGLE_OF_ATTACK, 329.2, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_0, CAMERA_FIELD_TARGET_DISTANCE, 1500.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_0, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_0, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_0, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_welcome_0, -800.9, 4425.8, 0.0 )

    set gg_cam_welcome_1 = CreateCameraSetup(  )
    call CameraSetupSetField( gg_cam_welcome_1, CAMERA_FIELD_ZOFFSET, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_1, CAMERA_FIELD_ROTATION, 90.5, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_1, CAMERA_FIELD_ANGLE_OF_ATTACK, 349.3, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_1, CAMERA_FIELD_TARGET_DISTANCE, 846.7, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_1, CAMERA_FIELD_ROLL, 0.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_1, CAMERA_FIELD_FIELD_OF_VIEW, 70.0, 0.0 )
    call CameraSetupSetField( gg_cam_welcome_1, CAMERA_FIELD_FARZ, 5000.0, 0.0 )
    call CameraSetupSetDestPosition( gg_cam_welcome_1, -938.0, 4873.6, 0.0 )

endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************
//TESH.scrollpos=0
//TESH.alwaysfold=0
//! import "Import Dmdf.j"
//! import "Gardonar/Import.j"
//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Traps 0
//===========================================================================
function Trig_Traps_0_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_0_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1660, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1659, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1700, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1658, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_0), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[0] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_0), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[0] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1660, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1659, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1700, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1658, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_0 takes nothing returns nothing
    set gg_trg_Traps_0 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_0, gg_rct_trap_0 )
    call TriggerAddCondition( gg_trg_Traps_0, Condition( function Trig_Traps_0_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_0, function Trig_Traps_0_Actions )
endfunction

//===========================================================================
// Trigger: Traps 1
//===========================================================================
function Trig_Traps_1_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_1_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1727, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1725, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1728, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1726, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_1), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[1] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_1), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[1] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1727, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1725, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1728, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1726, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_1 takes nothing returns nothing
    set gg_trg_Traps_1 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_1, gg_rct_trap_1 )
    call TriggerAddCondition( gg_trg_Traps_1, Condition( function Trig_Traps_1_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_1, function Trig_Traps_1_Actions )
endfunction

//===========================================================================
// Trigger: Traps 2
//===========================================================================
function Trig_Traps_2_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_2_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1721, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1720, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1722, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1723, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_2), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[2] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_2), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[2] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1721, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1720, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1722, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_1723, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_2 takes nothing returns nothing
    set gg_trg_Traps_2 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_2, gg_rct_trap_2 )
    call TriggerAddCondition( gg_trg_Traps_2, Condition( function Trig_Traps_2_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_2, function Trig_Traps_2_Actions )
endfunction

//===========================================================================
// Trigger: Traps 3
//===========================================================================
function Trig_Traps_3_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_3_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2145, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2146, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2144, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2147, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_3), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[3] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_3), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[3] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2145, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2146, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2144, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2147, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_3 takes nothing returns nothing
    set gg_trg_Traps_3 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_3, gg_rct_trap_3 )
    call TriggerAddCondition( gg_trg_Traps_3, Condition( function Trig_Traps_3_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_3, function Trig_Traps_3_Actions )
endfunction

//===========================================================================
// Trigger: Traps 4
//===========================================================================
function Trig_Traps_4_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_4_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2148, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2149, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2150, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2151, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_4), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[4] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_4), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[4] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2148, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2149, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2150, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2151, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_4 takes nothing returns nothing
    set gg_trg_Traps_4 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_4, gg_rct_trap_4 )
    call TriggerAddCondition( gg_trg_Traps_4, Condition( function Trig_Traps_4_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_4, function Trig_Traps_4_Actions )
endfunction

//===========================================================================
// Trigger: Traps 5
//===========================================================================
function Trig_Traps_5_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_5_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2152, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2153, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2154, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2155, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_7), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[5] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_7), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[5] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2152, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2153, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2154, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2155, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_5 takes nothing returns nothing
    set gg_trg_Traps_5 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_5, gg_rct_trap_7 )
    call TriggerAddCondition( gg_trg_Traps_5, Condition( function Trig_Traps_5_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_5, function Trig_Traps_5_Actions )
endfunction

//===========================================================================
// Trigger: Traps 6
//===========================================================================
function Trig_Traps_6_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_6_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2156, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2157, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2158, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2159, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_5), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[6] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_5), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[6] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2156, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2157, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2158, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2159, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_6 takes nothing returns nothing
    set gg_trg_Traps_6 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_6, gg_rct_trap_5 )
    call TriggerAddCondition( gg_trg_Traps_6, Condition( function Trig_Traps_6_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_6, function Trig_Traps_6_Actions )
endfunction

//===========================================================================
// Trigger: Traps 7
//===========================================================================
function Trig_Traps_7_Conditions takes nothing returns boolean
    if ( not ( GetOwningPlayer(GetTriggerUnit()) != Player(PLAYER_NEUTRAL_AGGRESSIVE) ) ) then
        return false
    endif
    return true
endfunction

function Trig_Traps_7_Actions takes nothing returns nothing
    call DisableTrigger( GetTriggeringTrigger() )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2160, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2161, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2162, "Death" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2163, "Death" )
    call AddSpecialEffectLocBJ( GetRectCenter(gg_rct_trap_6), "Abilities\\Spells\\Human\\FlameStrike\\FlameStrike1.mdl" )
    set udg_trapeffect[7] = GetLastCreatedEffectBJ()
    call UnitDamagePointLoc( gg_unit_n06U_0005, 0, 500, GetRectCenter(gg_rct_trap_6), 900.00, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_FIRE )
    call TriggerSleepAction( 4.00 )
    call DestroyEffectBJ( udg_trapeffect[7] )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2160, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2161, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2162, "Stand" )
    call SetDestructableAnimationBJ( gg_dest_DTfp_2163, "Stand" )
    call EnableTrigger( GetTriggeringTrigger() )
endfunction

//===========================================================================
function InitTrig_Traps_7 takes nothing returns nothing
    set gg_trg_Traps_7 = CreateTrigger(  )
    call TriggerRegisterEnterRectSimple( gg_trg_Traps_7, gg_rct_trap_6 )
    call TriggerAddCondition( gg_trg_Traps_7, Condition( function Trig_Traps_7_Conditions ) )
    call TriggerAddAction( gg_trg_Traps_7, function Trig_Traps_7_Actions )
endfunction

//===========================================================================
// Trigger: Intro
//===========================================================================
function Trig_Intro_Actions takes nothing returns nothing
    call CameraSetupApplyForPlayer( true, gg_cam_intro_0, Player(0), 0 )
    call TriggerSleepAction( 3.50 )
    call CameraSetupApplyForPlayer( true, gg_cam_intro_1, Player(0), 0 )
endfunction

//===========================================================================
function InitTrig_Intro takes nothing returns nothing
    set gg_trg_Intro = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Intro, function Trig_Intro_Actions )
endfunction

//===========================================================================
// Trigger: The Gate
//===========================================================================
function Trig_The_Gate_Actions takes nothing returns nothing
    call CameraSetupApplyForPlayer( true, gg_cam_the_gate_0, Player(0), 0 )
    call CameraSetupApplyForPlayer( true, gg_cam_the_gate_1, Player(0), 4.00 )
    call TriggerSleepAction( 3.50 )
    call CameraSetupApplyForPlayer( true, gg_cam_the_gate_2, Player(0), 2.00 )
    call TriggerSleepAction( 1.50 )
    call CameraSetupApplyForPlayer( true, gg_cam_the_gate_3, Player(0), 4.00 )
    call TriggerSleepAction( 3.50 )
    // Die Wächterinnen machen sich über die Ankömmlinge lustig, lassen sie aber passieren
    call TriggerSleepAction( 3.50 )
    call CameraSetupApplyForPlayer( true, gg_cam_the_gate_4, Player(0), 4.00 )
    call TriggerSleepAction( 3.50 )
endfunction

//===========================================================================
function InitTrig_The_Gate takes nothing returns nothing
    set gg_trg_The_Gate = CreateTrigger(  )
    call TriggerAddAction( gg_trg_The_Gate, function Trig_The_Gate_Actions )
endfunction

//===========================================================================
// Trigger: Shrines
//===========================================================================
function Trig_Shrines_Actions takes nothing returns nothing
    call KillUnit( gg_unit_n02D_0064 )
    call KillDestructable( gg_dest_B008_0133 )
    call KillUnit( gg_unit_n02D_0085 )
    call KillDestructable( gg_dest_B008_0267 )
endfunction

//===========================================================================
function InitTrig_Shrines takes nothing returns nothing
    set gg_trg_Shrines = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Shrines, function Trig_Shrines_Actions )
endfunction

//===========================================================================
// Trigger: Npcs
//===========================================================================
function Trig_Npcs_Actions takes nothing returns nothing
    call KillUnit( gg_unit_H01F_0004 )
    call KillUnit( gg_unit_H01E_0009 )
    call KillUnit( gg_unit_H01C_0003 )
endfunction

//===========================================================================
function InitTrig_Npcs takes nothing returns nothing
    set gg_trg_Npcs = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Npcs, function Trig_Npcs_Actions )
endfunction

//===========================================================================
// Trigger: Palace
//===========================================================================
function Trig_Palace_Actions takes nothing returns nothing
    call KillDestructable( gg_dest_DTg5_0000 )
    call KillUnit( gg_unit_n06Y_0023 )
    call KillUnit( gg_unit_n06Y_0024 )
    call KillUnit( gg_unit_n06X_0016 )
    call KillUnit( gg_unit_n06X_0017 )
    call KillUnit( gg_unit_n070_0035 )
    call KillUnit( gg_unit_n070_0034 )
endfunction

//===========================================================================
function InitTrig_Palace takes nothing returns nothing
    set gg_trg_Palace = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Palace, function Trig_Palace_Actions )
endfunction

//===========================================================================
// Trigger: Demon Heroes
//===========================================================================
function Trig_Demon_Heroes_Actions takes nothing returns nothing
    call KillUnit( gg_unit_n06U_0005 )
    call KillUnit( gg_unit_u00A_0006 )
    call KillUnit( gg_unit_n06W_0007 )
    call KillUnit( gg_unit_n06V_0008 )
endfunction

//===========================================================================
function InitTrig_Demon_Heroes takes nothing returns nothing
    set gg_trg_Demon_Heroes = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Demon_Heroes, function Trig_Demon_Heroes_Actions )
endfunction

//===========================================================================
// Trigger: Spawns
//===========================================================================
function Trig_Spawns_Actions takes nothing returns nothing
    // Demons 4
    call RemoveUnit( gg_unit_n07B_0126 )
    call RemoveUnit( gg_unit_n07B_0125 )
    call RemoveUnit( gg_unit_n073_0130 )
    call RemoveUnit( gg_unit_n073_0131 )
    call RemoveUnit( gg_unit_n073_0132 )
    call RemoveUnit( gg_unit_n078_0123 )
    call RemoveUnit( gg_unit_n078_0124 )
    call RemoveUnit( gg_unit_n072_0122 )
    call RemoveUnit( gg_unit_n072_0122 )
    call RemoveUnit( gg_unit_n072_0121 )
    call RemoveUnit( gg_unit_n07A_0129 )
    call RemoveUnit( gg_unit_n07A_0128 )
    call RemoveUnit( gg_unit_n07A_0127 )
    call RemoveUnit( gg_unit_n04C_0154 )
    call RemoveUnit( gg_unit_n04C_0155 )
    call RemoveUnit( gg_unit_n04D_0156 )
    call RemoveUnit( gg_unit_n02C_0157 )
    call RemoveUnit( gg_unit_n02C_0158 )
    // Demons 3
    call RemoveUnit( gg_unit_n07B_0117 )
    call RemoveUnit( gg_unit_n07B_0118 )
    call RemoveUnit( gg_unit_n07B_0119 )
    call RemoveUnit( gg_unit_n04C_0153 )
    call RemoveUnit( gg_unit_n04D_0151 )
    call RemoveUnit( gg_unit_n04D_0152 )
    call RemoveUnit( gg_unit_n04D_0150 )
    // Demons 2
    call RemoveUnit( gg_unit_n079_0114 )
    call RemoveUnit( gg_unit_n079_0115 )
    call RemoveUnit( gg_unit_n079_0116 )
    call RemoveUnit( gg_unit_n078_0099 )
    call RemoveUnit( gg_unit_n078_0100 )
    call RemoveUnit( gg_unit_n078_0101 )
    call RemoveUnit( gg_unit_n078_0102 )
    call RemoveUnit( gg_unit_n078_0103 )
    call RemoveUnit( gg_unit_n078_0104 )
    call RemoveUnit( gg_unit_n078_0105 )
    call RemoveUnit( gg_unit_n078_0106 )
    call RemoveUnit( gg_unit_n078_0107 )
    call RemoveUnit( gg_unit_n078_0108 )
    call RemoveUnit( gg_unit_n078_0109 )
    call RemoveUnit( gg_unit_n078_0110 )
    call RemoveUnit( gg_unit_n078_0111 )
    call RemoveUnit( gg_unit_n078_0112 )
    call RemoveUnit( gg_unit_n078_0113 )
    call RemoveUnit( gg_unit_n02C_0143 )
    call RemoveUnit( gg_unit_n02C_0142 )
    call RemoveUnit( gg_unit_n02C_0144 )
    call RemoveUnit( gg_unit_n032_0148 )
    call RemoveUnit( gg_unit_n032_0149 )
    call RemoveUnit( gg_unit_n02C_0146 )
    call RemoveUnit( gg_unit_n02C_0147 )
    call RemoveUnit( gg_unit_n02C_0145 )
    // Demons 1
    call RemoveUnit( gg_unit_n07A_0095 )
    call RemoveUnit( gg_unit_n07A_0096 )
    call RemoveUnit( gg_unit_n07B_0097 )
    call RemoveUnit( gg_unit_n04D_0141 )
    call RemoveUnit( gg_unit_n04C_0139 )
    call RemoveUnit( gg_unit_n04C_0140 )
    call RemoveUnit( gg_unit_n07B_0098 )
    call RemoveUnit( gg_unit_n07A_0094 )
    call RemoveUnit( gg_unit_n07A_0093 )
    call RemoveUnit( gg_unit_n07A_0092 )
    call RemoveUnit( gg_unit_n04B_0138 )
    call RemoveUnit( gg_unit_n04B_0137 )
    call RemoveUnit( gg_unit_n04B_0136 )
    // Hell Servants 2
    call RemoveUnit( gg_unit_n073_0089 )
    call RemoveUnit( gg_unit_n073_0087 )
    call RemoveUnit( gg_unit_n073_0088 )
    call RemoveUnit( gg_unit_n073_0090 )
    call RemoveUnit( gg_unit_n073_0091 )
    // Hell Servants 1
    call RemoveUnit( gg_unit_n073_0080 )
    call RemoveUnit( gg_unit_n073_0083 )
    call RemoveUnit( gg_unit_n073_0084 )
    call RemoveUnit( gg_unit_n073_0075 )
    call RemoveUnit( gg_unit_n073_0074 )
    call RemoveUnit( gg_unit_n073_0072 )
    call RemoveUnit( gg_unit_n073_0071 )
    call RemoveUnit( gg_unit_n073_0079 )
    call RemoveUnit( gg_unit_n073_0070 )
    call RemoveUnit( gg_unit_n073_0081 )
    call RemoveUnit( gg_unit_n073_0082 )
    call RemoveUnit( gg_unit_n073_0077 )
    call RemoveUnit( gg_unit_n073_0078 )
    call RemoveUnit( gg_unit_n073_0069 )
    call RemoveUnit( gg_unit_n073_0076 )
    call RemoveUnit( gg_unit_n073_0073 )
    // Demon Beast
    call RemoveUnit( gg_unit_n073_0057 )
    call RemoveUnit( gg_unit_n073_0053 )
    call RemoveUnit( gg_unit_n073_0044 )
    call RemoveUnit( gg_unit_n073_0045 )
    call RemoveUnit( gg_unit_n073_0043 )
    call RemoveUnit( gg_unit_n073_0055 )
    call RemoveUnit( gg_unit_n073_0052 )
    call RemoveUnit( gg_unit_n073_0048 )
    call RemoveUnit( gg_unit_n073_0050 )
    call RemoveUnit( gg_unit_n073_0058 )
    call RemoveUnit( gg_unit_n073_0056 )
    call RemoveUnit( gg_unit_n073_0059 )
    call RemoveUnit( gg_unit_n073_0051 )
    call RemoveUnit( gg_unit_n073_0047 )
    call RemoveUnit( gg_unit_n073_0054 )
    call RemoveUnit( gg_unit_n073_0046 )
    call RemoveUnit( gg_unit_n073_0049 )
    call RemoveUnit( gg_unit_n073_0060 )
    call RemoveUnit( gg_unit_n071_0039 )
    // Fire Demon
    call RemoveUnit( gg_unit_n072_0040 )
    call RemoveUnit( gg_unit_n072_0042 )
    call RemoveUnit( gg_unit_n072_0041 )
    // Boxes 1
    call RemoveUnit( gg_unit_n04D_0067 )
    call RemoveUnit( gg_unit_n04C_0068 )
    call RemoveUnit( gg_unit_n04D_0065 )
    call RemoveUnit( gg_unit_n04D_0066 )
    // Boxes 1
    call RemoveUnit( gg_unit_n04C_0063 )
    call RemoveUnit( gg_unit_n04D_0062 )
    call RemoveUnit( gg_unit_n04D_0061 )
endfunction

//===========================================================================
function InitTrig_Spawns takes nothing returns nothing
    set gg_trg_Spawns = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Spawns, function Trig_Spawns_Actions )
endfunction

//===========================================================================
// Trigger: Goldmine
//===========================================================================
function Trig_Goldmine_Actions takes nothing returns nothing
    call KillUnit( gg_unit_n06E_0161 )
endfunction

//===========================================================================
function InitTrig_Goldmine takes nothing returns nothing
    set gg_trg_Goldmine = CreateTrigger(  )
    call TriggerAddAction( gg_trg_Goldmine, function Trig_Goldmine_Actions )
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Traps_0(  )
    call InitTrig_Traps_1(  )
    call InitTrig_Traps_2(  )
    call InitTrig_Traps_3(  )
    call InitTrig_Traps_4(  )
    call InitTrig_Traps_5(  )
    call InitTrig_Traps_6(  )
    call InitTrig_Traps_7(  )
    call InitTrig_Intro(  )
    call InitTrig_The_Gate(  )
    call InitTrig_Shrines(  )
    call InitTrig_Npcs(  )
    call InitTrig_Palace(  )
    call InitTrig_Demon_Heroes(  )
    call InitTrig_Spawns(  )
    call InitTrig_Goldmine(  )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call ForcePlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), false )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

    // Player 1
    call SetPlayerStartLocation( Player(1), 1 )
    call ForcePlayerStartLocation( Player(1), 1 )
    call SetPlayerColor( Player(1), ConvertPlayerColor(1) )
    call SetPlayerRacePreference( Player(1), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(1), false )
    call SetPlayerController( Player(1), MAP_CONTROL_USER )

    // Player 2
    call SetPlayerStartLocation( Player(2), 2 )
    call ForcePlayerStartLocation( Player(2), 2 )
    call SetPlayerColor( Player(2), ConvertPlayerColor(2) )
    call SetPlayerRacePreference( Player(2), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(2), false )
    call SetPlayerController( Player(2), MAP_CONTROL_USER )

    // Player 3
    call SetPlayerStartLocation( Player(3), 3 )
    call ForcePlayerStartLocation( Player(3), 3 )
    call SetPlayerColor( Player(3), ConvertPlayerColor(3) )
    call SetPlayerRacePreference( Player(3), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(3), false )
    call SetPlayerController( Player(3), MAP_CONTROL_USER )

    // Player 4
    call SetPlayerStartLocation( Player(4), 4 )
    call ForcePlayerStartLocation( Player(4), 4 )
    call SetPlayerColor( Player(4), ConvertPlayerColor(4) )
    call SetPlayerRacePreference( Player(4), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(4), false )
    call SetPlayerController( Player(4), MAP_CONTROL_USER )

    // Player 5
    call SetPlayerStartLocation( Player(5), 5 )
    call ForcePlayerStartLocation( Player(5), 5 )
    call SetPlayerColor( Player(5), ConvertPlayerColor(5) )
    call SetPlayerRacePreference( Player(5), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(5), false )
    call SetPlayerController( Player(5), MAP_CONTROL_USER )

    // Player 6
    call SetPlayerStartLocation( Player(6), 6 )
    call ForcePlayerStartLocation( Player(6), 6 )
    call SetPlayerColor( Player(6), ConvertPlayerColor(6) )
    call SetPlayerRacePreference( Player(6), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(6), false )
    call SetPlayerController( Player(6), MAP_CONTROL_NEUTRAL )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_19656
    call SetPlayerTeam( Player(0), 0 )
    call SetPlayerState( Player(0), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(1), 0 )
    call SetPlayerState( Player(1), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(2), 0 )
    call SetPlayerState( Player(2), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(3), 0 )
    call SetPlayerState( Player(3), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(4), 0 )
    call SetPlayerState( Player(4), PLAYER_STATE_ALLIED_VICTORY, 1 )
    call SetPlayerTeam( Player(5), 0 )
    call SetPlayerState( Player(5), PLAYER_STATE_ALLIED_VICTORY, 1 )

    //   Allied
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(0), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(1), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(2), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateAllyBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(0), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(1), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(2), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateAllyBJ( Player(5), Player(4), true )

    //   Shared Vision
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(0), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(1), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(2), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(4), true )
    call SetPlayerAllianceStateVisionBJ( Player(3), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(4), Player(5), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(0), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(1), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(2), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(3), true )
    call SetPlayerAllianceStateVisionBJ( Player(5), Player(4), true )

    // Force: TRIGSTR_19655
    call SetPlayerTeam( Player(6), 1 )
    call SetPlayerState( Player(6), PLAYER_STATE_ALLIED_VICTORY, 1 )

endfunction

function InitAllyPriorities takes nothing returns nothing

    call SetStartLocPrioCount( 0, 5 )
    call SetStartLocPrio( 0, 0, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 1, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 2, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 3, 4, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 0, 4, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 1, 5 )
    call SetStartLocPrio( 1, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 1, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 2, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 3, 4, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 1, 4, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 2, 5 )
    call SetStartLocPrio( 2, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 2, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 3, 4, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 2, 4, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 3, 5 )
    call SetStartLocPrio( 3, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 2, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 3, 4, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 3, 4, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 4, 5 )
    call SetStartLocPrio( 4, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 2, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 3, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 4, 4, 5, MAP_LOC_PRIO_HIGH )

    call SetStartLocPrioCount( 5, 5 )
    call SetStartLocPrio( 5, 0, 0, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 5, 1, 1, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 5, 2, 2, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 5, 3, 3, MAP_LOC_PRIO_HIGH )
    call SetStartLocPrio( 5, 4, 4, MAP_LOC_PRIO_HIGH )
endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -4608.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 11520.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 11264.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 11264.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 11520.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -4608.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCDungeon\\DNCDungeonTerrain\\DNCDungeonTerrain.mdl", "Environment\\DNC\\DNCDungeon\\DNCDungeonUnit\\DNCDungeonUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "DungeonDay" )
    call SetAmbientNightSound( "DungeonNight" )
    call SetMapMusic( "Music", true, 0 )
    call InitSounds(  )
    call CreateRegions(  )
    call CreateCameras(  )
    call CreateAllDestructables(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_17246" )
    call SetMapDescription( "TRIGSTR_17248" )
    call SetPlayers( 7 )
    call SetTeams( 7 )
    call SetGamePlacement( MAP_PLACEMENT_TEAMS_TOGETHER )

    call DefineStartLocation( 0, -1600.0, 128.0 )
    call DefineStartLocation( 1, -1600.0, 128.0 )
    call DefineStartLocation( 2, -1600.0, 128.0 )
    call DefineStartLocation( 3, -1600.0, 128.0 )
    call DefineStartLocation( 4, -1600.0, 128.0 )
    call DefineStartLocation( 5, -1600.0, 128.0 )
    call DefineStartLocation( 6, -1600.0, 128.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call InitCustomTeams(  )
    call InitAllyPriorities(  )
endfunction

